import { promises as fs } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const outFile = path.join(root, 'ASSET_AUDIT.md');
const assetExts = new Set(['.png', '.jpg', '.jpeg', '.webp', '.gif', '.svg', '.mp3', '.ogg', '.wav', '.m4a', '.flac']);
const sourceExts = new Set(['.js', '.jsx', '.ts', '.tsx', '.css', '.json', '.html', '.md']);
const ignoreDirs = new Set(['node_modules', 'dist', '.git', '.next', '.vite', 'coverage']);
const suspiciousName = /(?:old|temp|placeholder|draft|copy|backup|low|unused|test|sample|pixel|small|legacy)/i;

async function walk(dir, files = []) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (ignoreDirs.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) await walk(full, files);
    else files.push(full);
  }
  return files;
}

function rel(file) {
  return path.relative(root, file).replaceAll(path.sep, '/');
}

function humanBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
}

function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function referenceNeedles(assetRel) {
  const base = path.basename(assetRel);
  const noPublic = assetRel.replace(/^public\//, '/');
  const noSrc = assetRel.replace(/^src\//, '');
  return Array.from(new Set([assetRel, noPublic, noSrc, base]));
}

async function main() {
  const all = await walk(root);
  const assets = [];
  const sourceFiles = [];

  for (const file of all) {
    const ext = path.extname(file).toLowerCase();
    if (assetExts.has(ext)) {
      const stat = await fs.stat(file);
      assets.push({ file, rel: rel(file), ext, size: stat.size });
    } else if (sourceExts.has(ext)) {
      sourceFiles.push(file);
    }
  }

  const sourceCache = new Map();
  for (const file of sourceFiles) {
    try { sourceCache.set(file, await fs.readFile(file, 'utf8')); }
    catch { sourceCache.set(file, ''); }
  }

  const rows = assets.map((asset) => {
    const refs = [];
    const needles = referenceNeedles(asset.rel).filter(Boolean);
    for (const [sourceFile, text] of sourceCache.entries()) {
      if (sourceFile === asset.file) continue;
      if (needles.some((needle) => new RegExp(escapeRegExp(needle), 'i').test(text))) refs.push(rel(sourceFile));
    }
    return {
      ...asset,
      refs: Array.from(new Set(refs)).sort(),
      suspicious: suspiciousName.test(asset.rel),
    };
  }).sort((a, b) => a.rel.localeCompare(b.rel));

  const referenced = rows.filter((row) => row.refs.length > 0);
  const unreferenced = rows.filter((row) => row.refs.length === 0);
  const large = rows.filter((row) => row.size >= 500 * 1024).sort((a, b) => b.size - a.size);
  const suspicious = rows.filter((row) => row.suspicious);
  const duplicateGroups = Object.values(rows.reduce((acc, row) => {
    const key = path.basename(row.rel).toLowerCase().replace(/[-_ ]?(copy|old|backup|draft|temp|low|small|\d+)\b/g, '');
    acc[key] ||= [];
    acc[key].push(row);
    return acc;
  }, {})).filter((group) => group.length > 1);

  const lines = [];
  lines.push('# Shattered Veil Asset Audit');
  lines.push('');
  lines.push(`Generated by \`npm run audit:assets\`.`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`- Total assets: ${rows.length}`);
  lines.push(`- Referenced assets: ${referenced.length}`);
  lines.push(`- Possibly unreferenced assets: ${unreferenced.length}`);
  lines.push(`- Large assets (>= 500 KB): ${large.length}`);
  lines.push(`- Suspected old/placeholder/low-res assets: ${suspicious.length}`);
  lines.push(`- Duplicate or near-duplicate filename groups: ${duplicateGroups.length}`);
  lines.push('');
  lines.push('## Confirmed Referenced Assets');
  lines.push('');
  for (const row of referenced.slice(0, 250)) {
    lines.push(`- \`${row.rel}\` (${humanBytes(row.size)}) — referenced in ${row.refs.slice(0, 5).map((r) => `\`${r}\``).join(', ')}${row.refs.length > 5 ? ` and ${row.refs.length - 5} more` : ''}`);
  }
  if (referenced.length > 250) lines.push(`- ...${referenced.length - 250} additional referenced assets omitted for readability.`);
  lines.push('');
  lines.push('## Possibly Unreferenced Assets');
  lines.push('');
  lines.push('These should be manually reviewed before any deletion. Dynamic references, CSS-generated URLs, save data, or future content may not be detected.');
  lines.push('');
  for (const row of unreferenced.slice(0, 250)) lines.push(`- \`${row.rel}\` (${humanBytes(row.size)})`);
  if (unreferenced.length > 250) lines.push(`- ...${unreferenced.length - 250} additional possibly unreferenced assets omitted for readability.`);
  lines.push('');
  lines.push('## Large Assets');
  lines.push('');
  for (const row of large.slice(0, 100)) lines.push(`- \`${row.rel}\` — ${humanBytes(row.size)} — ${row.refs.length ? 'referenced' : 'possibly unreferenced'}`);
  lines.push('');
  lines.push('## Duplicate or Near-Duplicate Filenames');
  lines.push('');
  for (const group of duplicateGroups.slice(0, 100)) {
    lines.push(`- ${group.map((row) => `\`${row.rel}\` (${humanBytes(row.size)})`).join(' / ')}`);
  }
  lines.push('');
  lines.push('## Suspected Placeholder / Old / Low-Resolution Assets');
  lines.push('');
  for (const row of suspicious.slice(0, 150)) lines.push(`- \`${row.rel}\` (${humanBytes(row.size)}) — ${row.refs.length ? 'referenced' : 'possibly unreferenced'}`);
  lines.push('');
  lines.push('## High-Risk Assets That Should Not Be Deleted Yet');
  lines.push('');
  lines.push('- Any asset under `public/` or `src/` that appears unreferenced but may be loaded dynamically.');
  lines.push('- Any music/audio file until the intended high-quality audio route is verified.');
  lines.push('- Any map, class, character, terrain, or battle image until screenshots confirm it is obsolete.');
  lines.push('- Any asset referenced by generated data, saves, localStorage, or server payloads.');
  lines.push('');
  lines.push('## Recommended Next Cleanup Steps');
  lines.push('');
  lines.push('1. Manually review the possibly unreferenced list before deletion.');
  lines.push('2. Prioritize large referenced assets for compression or modern format replacement only after visual comparison.');
  lines.push('3. Replace old/low/placeholder assets through explicit manifest routing first, not by deleting files.');
  lines.push('4. Add confirmed critical battle/map/create assets to the P3 priority preload manifest.');
  lines.push('5. Keep deletions in separate PRs with screenshots and rollback notes.');
  lines.push('');

  await fs.writeFile(outFile, `${lines.join('\n')}\n`, 'utf8');
  console.log(`Wrote ${path.relative(root, outFile)} with ${rows.length} assets.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
